default: &default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  telegram:
    bot:
      token: <%= ENV['TELEGRAM_TOKEN'] %>
      username: <%= ENV['TELEGRAM_BOT'] %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
